// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiedneggzimmfrdjwjqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZWRuZWdnemltbWZyZGp3anF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjExMDksImV4cCI6MjA1ODU5NzEwOX0.7NRdATQoyj43UyINbTlzFAOpoBuIZ3RUHyzmRcO4wDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);